# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-16 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, db_column='alert_id', primary_key=True, serialize=False)),
                ('temperature', models.FloatField(db_column='temperature')),
                ('ph', models.FloatField(db_column='ph')),
                ('pressure', models.FloatField(db_column='pressure')),
                ('electrolytic', models.BooleanField(db_column='electrolytic', default=False)),
            ],
            options={
                'db_table': 'alert',
            },
        ),
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.AutoField(auto_created=True, db_column='water_id', primary_key=True, serialize=False)),
                ('curTime', models.DateField(auto_now=True, db_column='cur_time')),
                ('temperature', models.FloatField(db_column='water_temperature')),
                ('ph', models.FloatField(db_column='water_ph')),
                ('pressure', models.FloatField(db_column='water_pressure')),
                ('electrolytic', models.BooleanField(db_column='water_electrolytic', default=False)),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'water',
            },
        ),
    ]
